import type { Metadata } from 'next';
import { JSX } from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'CCEP',
  description: 'Generated by create next app',
};

interface Props {
  children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<Props>): JSX.Element {
  return (
    <html lang='en'>
      <body className={`font-you antialiased`}>{children}</body>
    </html>
  );
}
